{
    "data":{
        "seniority_number":10
        "employee_number":301239
        "doh":"02\/08\/1995"
        "seat":"CA"
        "fleet":"747"
        "domicile":"MIA"
        "retire":"04\/25\/2027"
        "status":3
        "month":"Mar 2023"
        "award":{
            "employee_number":301239
            "award_domicile":"ORD",
            "award_fleet":"747",
            "award_seat":"CA"
        }
    }
}